# cloudbuild.yaml
# A complete CI/CD pipeline for the M&S Demand Forecasting model.

steps:
# Step 1: Install dependencies and run unit tests to ensure code quality.
- name: 'python:3.9'
  id: 'Run Tests'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    pip install -r requirements.txt
    pytest tests/

# Step 2: Build the Docker image, tagging it with the unique Git commit hash for traceability.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  args: [
    'build',
    '-t',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}',
    '.'
    ]

# Step 3: Push the versioned container image to Google Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Image'
  args: [
    'push',
    '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
    ]

# Step 4: Dynamically update the pipeline definition to use the new image URI.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Update Pipeline Spec'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    sed -i "s|DOCKER_IMAGE_URI = .*|DOCKER_IMAGE_URI = \"${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}\"|" src/pipeline.py

# Step 5: Force an update of the gcloud SDK and trigger the Vertex AI Pipeline.
# This ensures the most recent components (including 'ai pipelines') are available.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Trigger Pipeline'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "Forcing gcloud components update to ensure 'ai pipelines' command is available..."
    gcloud components update
    
    echo "Triggering Vertex AI Pipeline..."
    gcloud ai pipelines run \
      --region=${_REGION} \
      --display-name="demand-forecast-ci-cd-run-${SHORT_SHA}" \
      --pipeline-spec-path=src/pipeline.py \
      --parameter-file=params.yaml

# This lists the final image URI in the build artifacts for reference.
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

# These are substitution variables that Cloud Build will use.
substitutions:
  _REGION: 'europe-west1'
  _REPO_NAME: 'forecasting-repo'
  _IMAGE_NAME: 'demand-forecaster'

# This option ensures logs are correctly streamed to Cloud Logging.
options:
  logging: CLOUD_LOGGING_ONLY
